services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin  # Опционально
      MONGO_INITDB_ROOT_PASSWORD: 12345  # Опционально

volumes:
  mongodb_data: